### PR TITLE
Add web app functions

### PR DESCRIPTION
**Pull request by kjhawekotte**
Let's do it. Finally. Merge the functions into master.

### CODE REVIEW

**Comment by NathanDeMaria** [comment]
I keep forgetting to look at this...I might actually have time this weekend.

If this code works for you...
image

**Comment by mwoodson1** [comment]
Hai guys!

**Comment by NathanDeMaria** [comment]
Markus!! How's life?

**Comment by mwoodson1** [comment]
Good! How's it going for you guys? Also this is a really weird medium to be
talking through lol

**Comment by NathanDeMaria** [comment]
It's going great! :smile:

**Pull request merged**
